# Site settings
title: Karthik Balakrishnan
email: karthikb351@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://karthikbalakrishnan.com" # the base hostname & protocol for your site

owner:
  name: Karthik Balakrishnan
  twitter: karthikb351
  facebook: karthikb351
  github:  karthikb351
  email: karthikb351@gmail.com

# Build settings
markdown: kramdown

sass:
    sass_dir: assets/css/_partials